CREATE TABLE POST_TAG (
  POSTS_ID int NOT NULL,
  TAGS_NAME varchar(255) NOT NULL,
  KEY FK_TAGS_NAME_KEY (TAGS_NAME),
  KEY FK_POST_ID (POSTS_ID)
) ENGINE=InnoDB;

CREATE TABLE TAG (
  NAME varchar(255) NOT NULL,
  PRIMARY KEY (NAME)
) ENGINE=InnoDB